spring.application.name=Email-Service


#server config
server.port=8082
server.servlet.context-path=/email

#custom config
#No use for this as I am using a local variable which SPRING can't inject.
#(This is the ideal way of defining a config variable -> signup.email)
#signup.email = ${Signup_Email}
#signup.password = ${Signup_Password}
#security.email =${Security_Email}
#security.password = ${Security_Password}